[package]
name = "jxl-loader"
version = "0.4.0"
# tombi: lint.rules.unused-noqa.disabled = true
# tombi: lint.rules.deprecated.disabled = true
authors = ["frabera"]
edition = "2024"
description = "JXL decoder for Typst."
readme = "README.md"
repository = "https://github.com/frabera/jxltypst"
license = "MIT"
categories = ["JPEG XL", "image", "jxl", "plugin", "typst", "wasm"]

[lib]
crate-type = ["cdylib"]

[dependencies]
jxl = { git = "https://github.com/libjxl/jxl-rs", rev = "f8a3147af9a367228c5898b262aa5a6118481e4b", default-features = false, features = ["simd128"] }  # 0.6.0
wasm-minimal-protocol = "0.2.0"

[profile.release]
opt-level = 3
strip = true
lto = "fat"
panic = "abort"
codegen-units = 1
