[package]
name = "jxl-loader"
version = "0.4.0"
# tombi: lint.rules.deprecated.disabled = true
authors = ["frabera"]
edition = "2024"
description = "JXL decoder for Typst."
readme = "README.md"
repository = "https://github.com/frabera/jxltypst"
license = "MIT"
categories = ["JPEG XL", "image", "jxl", "plugin", "typst", "wasm"]

[dependencies]
jxl = { git = "https://github.com/libjxl/jxl-rs", rev = "595a05fc66d4cdcd988c7bbfe14459d820aa3d45", version = "0.7.4", default-features = false, features = ["simd128"] }
wasm-minimal-protocol = "0.2.1"

[profile.release]
opt-level = 3
strip = true
lto = "fat"
panic = "abort"
codegen-units = 1
