#import "typst/lib.typ": image-jxl

#set document(date: datetime(day: 1, month: 1, year: 1970))
#set page(width: auto, height: auto, margin: auto, fill: rgb("#f5f5dc"))

#html.elem("style")[
  body {
  background-color: beige;
  }
]

#let file_list = (
  "test/conformance_test_images/alpha_nonpremultiplied.jxl",
  // "test/conformance_test_images/alpha_premultiplied.jxl",
  // "test/conformance_test_images/alpha_triangles.jxl",
  // "test/conformance_test_images/animation_icos4d.jxl",
  // "test/conformance_test_images/animation_icos4d_5.jxl",
  // "test/conformance_test_images/animation_newtons_cradle.jxl",
  // "test/conformance_test_images/animation_spline.jxl",
  // "test/conformance_test_images/animation_spline_5.jxl",
  // "test/conformance_test_images/bench_oriented_brg.jxl",
  // "test/conformance_test_images/bench_oriented_brg_5.jxl",
  // "test/conformance_test_images/bicycles.jxl",
  // "test/conformance_test_images/bike.jxl",
  // "test/conformance_test_images/bike_5.jxl",
  // "test/conformance_test_images/blendmodes.jxl",
  // "test/conformance_test_images/blendmodes_5.jxl",
  // "test/conformance_test_images/cafe.jxl",
  // "test/conformance_test_images/cafe_5.jxl",
  // // "test/conformance_test_images/cmyk_layers.jxl", // ! FAIL: wrong colours
  // "test/conformance_test_images/delta_palette.jxl",
  // "test/conformance_test_images/grayscale.jxl",
  // "test/conformance_test_images/grayscale_5.jxl",
  // "test/conformance_test_images/grayscale_jpeg.jxl",
  // "test/conformance_test_images/grayscale_jpeg_5.jxl",
  // "test/conformance_test_images/grayscale_public_university.jxl",
  // "test/conformance_test_images/lossless_pfm.jxl",
  // "test/conformance_test_images/lz77_flower.jxl",
  // "test/conformance_test_images/noise.jxl",
  // "test/conformance_test_images/noise_5.jxl",
  // "test/conformance_test_images/opsin_inverse.jxl",
  // "test/conformance_test_images/opsin_inverse_5.jxl",
  // "test/conformance_test_images/patches.jxl",
  // "test/conformance_test_images/patches_5.jxl",
  // "test/conformance_test_images/progressive.jxl",
  // "test/conformance_test_images/progressive_5.jxl",
  // "test/conformance_test_images/spot.jxl",
  // "test/conformance_test_images/sunset_logo.jxl",
  // "test/conformance_test_images/upsampling.jxl",
  // "test/conformance_test_images/upsampling_5.jxl",
  // "test/3x3a_srgb_lossless.jxl",
  // "test/3x3a_srgb_lossy.jxl",
  // "test/3x3_jpeg_recompression.jxl",
  // "test/3x3_srgb_lossless.jxl",
  // "test/3x3_srgb_lossy.jxl",
  // "test/8x8_noise.jxl",
  // "test/basic.jxl",
  // "test/candle.jxl",
  // "test/cropped_traffic_light.jxl",
  // "test/dice.jxl",
  // "test/efb.jxl",
  // "test/extra_channels.jxl",
  // "test/grayscale_patches_modular.jxl",
  // "test/grayscale_patches_var_dct.jxl",
  // "test/gray_alpha_lossless.jxl",
  // "test/green_queen_modular_e3.jxl",
  // "test/green_queen_vardct_e3.jxl",
  // "test/has_permutation.jxl",
  // "test/has_permutation_with_container.jxl",
  // "test/hdr_hlg_test.jxl",
  // "test/hdr_pq_test.jxl",
  // "test/invalid_animated_ooo_jxlp.jxl",
  // "test/issue648_palette0.jxl",
  // "test/issue728_minimal.jxl",
  // "test/issue772_blendbug.jxl",
  // "test/issue865_large_toc.jxl",
  // // "test/large_header.jxl", // ! FAIL: panic (WONTFIX)
  // "test/lossy_with_icc.jxl",
  // "test/multiple_layers_noise_spline.jxl",
  // "test/multiple_lf_420.jxl",
  // "test/named_frame_test.jxl",
  // "test/oddsize_ups.jxl",
  // "test/orientation1_identity.jxl",
  // "test/orientation2_flip_horizontal.jxl",
  // "test/orientation3_rotate_180.jxl",
  // "test/orientation4_flip_vertical.jxl",
  // "test/orientation5_transpose.jxl",
  // "test/orientation6_rotate_90_cw.jxl",
  // "test/orientation7_anti_transpose.jxl",
  // "test/orientation8_rotate_90_ccw.jxl",
  // "test/patch_y_out_of_bounds.jxl",
  // "test/pq_gradient.jxl",
  // "test/progressive_ac.jxl",
  // "test/small_grayscale_patches_modular.jxl",
  // "test/small_grayscale_patches_modular_with_icc.jxl",
  // "test/splines.jxl",
  // "test/spline_on_first_frame.jxl",
  "test/squeeze_alpha.jxl",
  "test/squeeze_edge.jxl",
  "test/squeeze_empty_residual.jxl",
  "test/stp2_520x260_d25_e6.jxl",
  "test/strategic_solid_blue.jxl",
  "test/tirr_photo.jxl",
  "test/tree_max_property_20.jxl",
  "test/upsampled_alpha.jxl",
  "test/with_icc.jxl",
  "test/with_preview.jxl",
  "test/zoltan_tasi_unsplash.jxl",
)

#for imagepath in file_list {
  [#imagepath]
  linebreak()
  image-jxl(path(imagepath))
  html.elem("img", attrs: (src: imagepath))
}
